spring.datasource.url=jdbc:mysql://root:PctixypZYGzFeKkMqlSPCGHVDQQxamLS@hayabusa.proxy.rlwy.net:57495/railway
spring.datasource.username=root
spring.datasource.password=PctixypZYGzFeKkMqlSPCGHVDQQxamLS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080